### ISSUE TITLE
Difficulty exporting Blender actions

### ISSUE THREAD

**Issue by donmccurdy** [Kupoman/blendergltf#103]
Not entirely sure I'm doing this right, but thought I'd share my struggles in case there's a bug or I'm misunderstanding Blender actions.

I'm trying to export a simple test scene with two Actions in Blender, and my goal is that each Action would become a distinct `gltf.animations` entry, so that they can be played back independently. Here's my test `.blend`, and the `.gltf` output:

[actions_test_gltf.zip](https://github.com/Kupoman/blendergltf/files/1326733/actions_test_gltf.zip)

The Blender file has two actions, each operating on a different object. A third object in the scene is not animated. The output glTF has 6 `animations`, with three entries named for each of the two actions. Each animation entry targets only one object. This seems wrong in two ways: (1) the third object shouldn't be targeted by any animation, and (2) if an action did target multiple objects (although these do not) the [channels should all be combined into a single glTF animation entry](https://github.com/KhronosGroup/COLLADA2GLTF/issues/66).

When attempting to load the glTF in three.js I get an error about invalid typed array length. No output or visible error from BabylonJS.

Thanks!

**Comment by Kupoman** [comment]
When exporting actions, blendergltf does not use the active action on an object. Instead all action and object pairs are checked for compatibility and exported. This would allow one armature to have multiple actions (e.g. walk, run, jump, etc.). This approach is not ideal, and we are working on ways to provide users better options when exporting animations.

That being said, the glTF output of this file is not even passing the validator, so there are also some bugs here. Thanks for the .blend file, I will start looking into fixing up some of the bugs it seems to be hitting. I suspect the bugs are related to animating Blender objects instead of bones, which is not well tested.

**Comment by Kupoman** [comment]
I have pushed a couple of animation fixes so that the glTF passes the validator and does not leave the scene in as bad of a state. Some more work will need to be done to better avoid manipulating the scene during animation export.

**Comment by Kupoman** [comment]
I have added some options for animation export in d5a2202b3b60bfc71f6ee57d940b55f74de3be9b. I think the new default behavior for objects that do not have armatures will be closer to what you expected.

**Comment by donmccurdy** [comment]
Thanks @Kupoman — the output looks valid, and the default export has two actions like I'm expecting, but when loading the glTF into https://gltf-viewer.donmccurdy.com/ (which uses THREE.GLTFLoader) the animation does nothing. Inspecting the animation data, it seems like both frames have the same data.

Here are updated .blend and .gltf output:

[actions_test_gltf.zip](https://github.com/Kupoman/blendergltf/files/1354395/actions_test_gltf.zip)

| default settings | result in three.js |
|---|---|
| ![screen shot 2017-10-03 at 7 12 17 pm](https://user-images.githubusercontent.com/1848368/31157326-f47c16a0-a86e-11e7-929f-8faf8bf1e91e.png) |  ![screen shot 2017-10-03 at 7 14 25 pm](https://user-images.githubusercontent.com/1848368/31157372-4911c660-a86f-11e7-87b6-006d4ad6f52d.png) |

^Note that in both frames, the cylinder's scale is `1,1,2` while it should be `1,1,1` in the first frame.

**Comment by Kupoman** [comment]
Found the problem. Turns out every frame of an object transformation ended up referencing the same matrix. Fixed with dadbbae83ad3cb5bf9b3328295bbf421f812620f. It looks like the same problem was already addressed for armature animations.

**Comment by donmccurdy** [comment]
Many thanks! It's working for me now. 😀
