### ISSUE TITLE
"TEXCOORD_" must end with an index

### ISSUE THREAD

**Issue by onox** [Kupoman/blendergltf#11]
In 1.0.1 of the spec `TEXCOORD_` must end with an index. See [meshes](https://github.com/KhronosGroup/glTF/tree/1.0.1/specification#meshes). So properties like "TEXCOORD_UVMap" are not allowed anymore. (And application-specific must start with an _)

Taking a quick look at the code, it seems babylon.js and three.js expect an integer after `TEXCOORD_`.

**Comment by onox** [comment]
Btw, why does blendergltf add 4 `TEXCOORD_*` properties per primitive? The few examples in the glTF repository seem to use just 1.

**Comment by Kupoman** [comment]
This is definitely an issue, and it makes using textures awkward right now.  I'll fix this in the threejs_improvements branch since I have to deal with some other material related issues there already.

**Comment by onox** [comment]
> I have to deal with some other material related issues there already.

I found some material related issues also. See #23 and #24.
