### ISSUE TITLE
Support for material selection names

### ISSUE THREAD

**Issue by fracteed** [Kupoman/blendergltf#110]
When exporting an obj from Blender to Godot3 I get the polygon/material selection names into Godot the same as they were named in Blender. If I try this with the gltf exporter I just get an integer for each selection. Is it possible to get these names in? Hard to say if it is a limitation of the exporter or the Godot gltf importer, as I have no other software that can open these files.

As can be seen from the following image, the 2 material selections in Blender (base, accent) come in as 0, 1 in Godot. 

![material_selections](https://user-images.githubusercontent.com/7741669/32259678-2ce3cbd8-bf16-11e7-9bca-f747a9fa453b.jpg)

**Comment by Moguri** [comment]
I think this may be a Godot issue since we do export material names. I wonder if Godot is using the index instead of the name?

**Comment by fracteed** [comment]
@Moguri thanks for the info. I will log an issue with Godot and see if it can be resolved their end.

**Comment by Kupoman** [comment]
@fracteed Were you able to determine if this was a bug with the Godot importer?

**Comment by fracteed** [comment]
@Kupoman I haven't filed an issue yet, and was going to wait till they hit beta/bug fix time. I can see the material names in the gltf file with a text editor, so it is likely a fault with Godot. Not sure what else will open a gltf file to check this.... Have you tried importing a file like this into any other DCC?

**Comment by Kupoman** [comment]
I have successfully imported material names into Panda3D. Since this does not look like a blendergltf bug, I am closing this issue. If this turns out to not be a problem with Godot's importer, please reopen this issue.

**Comment by fracteed** [comment]
Ok, thanks for letting me know!
