### ISSUE TITLE
Issues with multiple actions

### ISSUE THREAD

**Issue by tkazik** [Kupoman/blendergltf#120]
Hi folks

I have an aircraft model with multiple actions. All these actions together animate the gear up/down mechanism. Unfortunately, if I export the model using this exporter, I get lots of error messages and the animation is messed up. The export including animation runs fine with the Khronos exporter, which basically exports the timeline. But as I will add other actions in the future (e.g. flaps, spoilers etc.) I need to use actions to proceed and thus this exporter. 
Any hints and tips for me? Would greatly appreciate your effort and time!

Screenshot of the NLA editor:
![nla_actions](https://user-images.githubusercontent.com/15689124/34691494-0e6817ea-f4bd-11e7-91da-ae841c1b5861.png)
Would it help to create one single action for all of these? How would I do that in Blender?

Here is the model: 
[A319_generic_gearOnly.zip](https://github.com/Kupoman/blendergltf/files/1612993/A319_generic_gearOnly.zip)

**Comment by Kupoman** [comment]
At least for now, this exporter completely ignores the NLA editor.

Using the latest master, I exported the provided file with no errors. I was also able to see the landing gear animate in the [glTF Viewer](https://gltf-viewer.donmccurdy.com/) after selecting the play all option under animations. I only changed 3 exporter settings from the default. I enabled binary glTF, embedded buffers, and embedded images.

**Comment by tkazik** [comment]
Awesome, you are right! I must have had an old version...sorry for this report then.
Do you know by chance, if there is a way in blender, to group all these actions to one? This would make the control of the animation much easier. I was trying to bake all of them together but was out of luck.
Thank you very much! 

PS: Issue can be closed, thank you!
