### ISSUE TITLE
Shape Key Animations doesn't exported

### ISSUE THREAD

**Issue by apostololeg** [Kupoman/blendergltf#122]
Source: [monkey.blend](https://file.io/YVKacy)
Exporter params:
![2018-01-22_16-31-47](https://user-images.githubusercontent.com/514713/35223281-cf8b24c4-ff91-11e7-876e-ba64c620568a.png)

In fact, monkey.gltf contain no field "animation".

**Comment by Kupoman** [comment]
Looks like I got ahead of myself. Shape keys are exported as morph targets, but shape key animations are not currently exported. Adding this to the to-do list for 1.2, and hopefully I can get to it soon.

**Comment by apostololeg** [comment]
Big thanks for quick response ;)
For now, animation exported correctly, except that there is only one animation exported  https://github.com/Kupoman/blendergltf/issues/123
