### ISSUE TITLE
Exported only one Shape Key Animation

### ISSUE THREAD

**Issue by apostololeg** [Kupoman/blendergltf#123]
I have scene([monkey.blend](https://dl.dropboxusercontent.com/s/vhvj306wyn4v8c7/monkey.blend?dl=0)) with 2 Shape Key animations.
After exporting, `gltf.animations` contains only one animation, that was selected from the list in Blender ("eye" in this case).
![1](https://user-images.githubusercontent.com/514713/35379069-e6b8cfc6-01c5-11e8-88a5-35434d20f2ec.png)

Export Params 
![2](https://user-images.githubusercontent.com/514713/35379183-52b5302a-01c6-11e8-84dd-fdb98a37f207.png)

Out – [monkey.gltf](https://dl.dropboxusercontent.com/s/wo6a5mdxgtby3bi/monkey.gltf?dl=0)

**Comment by Kupoman** [comment]
Thanks for continuing to create these issues. I am thinking about adding another option under animations for shape keys to choose between exporting all eligible or just the active shape key animation. I think all eligible would be a good default for this setting.
