### ISSUE TITLE
Errors on exporting

### ISSUE THREAD

**Issue by sketchpunk** [Kupoman/blendergltf#126]
Trying to export a simple mesh, armature and a single action. Using Blender 2.79. I've supplied the blender file plus a screenshot of the error message that appears on the screen.

[bendy_v1_0_1b.zip](https://github.com/Kupoman/blendergltf/files/1708900/bendy_v1_0_1b.zip)
![err](https://user-images.githubusercontent.com/2301158/35999691-b44a3384-0cee-11e8-96ad-9f082cd3c8b6.png)

**Comment by nataliawojtkowska** [comment]
Can't export the mesh either just getting a different error message 
<img width="866" alt="screen shot 2018-02-13 at 10 58 27" src="https://user-images.githubusercontent.com/23186467/36144710-3dc9fd60-10af-11e8-97d2-6b79bf711aa8.png">

**Comment by Kupoman** [comment]
I was unable to reproduce this error using the latest master, supplied blend file, and default export settings. If you are using non-default settings, can you please provide them?

**Comment by sketchpunk** [comment]
download the latest, it now exports without error.  Noticed that in my game engine it does not export with Y up. I even tried using https://gltf-viewer.donmccurdy.com/ and the mesh renders 90 degrees on the x axis, so the mesh is facing down with -y as forward.

**Comment by Kupoman** [comment]
I did a quick export test and viewed the results in McCurdy's viewer, and the results were as I expected. Blender is z-up and y-forward, and glTF is y-up and z-forward.
