### ISSUE TITLE
Exporting Bezier Curve

### ISSUE THREAD

**Issue by apurvaojas** [Kupoman/blendergltf#128]
Unable to Export Bezier Curve with and without lofted object..?

Does This feature is present..?

**Comment by Kupoman** [comment]
This is not currently supported. I would recommend converting those objects to meshes before exporting.

**Comment by apurvaojas** [comment]
Is there any plan for adding this feature in future..?
As this is very useful for path animations.

**Comment by Kupoman** [comment]
Exporting Bezier curves is not on the road map, and would require an extension. Exporting curves as meshes is a more likely possibility. Would something like that be useful to you? Since I am trying to wrap things up for a 1.2 release, that feature would probably end up in the release after.

**Comment by Kupoman** [comment]
Closing this issue since Bezier curves are not supported, and are not a currently planned feature.
