### ISSUE TITLE
RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer

### ISSUE THREAD

**Issue by axandreo** [Kupoman/blendergltf#129]
I have a scene with with multiple animations when I export I get this RangeError. Here is my blender scene:

[bounce.zip](https://github.com/Kupoman/blendergltf/files/1751913/bounce.zip)

UPDATE:

putting the .gltf and the .bin into https://gltf-viewer.donmccurdy.com/

I get this: 

BUFFER_EXTERNAL_BYTELENGTH_MISMATCH | Actual data length 346044 is less than the declared buffer byteLength 376956. | /buffers/0

**Comment by Kupoman** [comment]
I am getting no errors using master and the default settings. The output file also passed the glTF validator, though I am likely using an old version of it. I also exported the file as a self contained binary and loaded it in that glTF viewer.

What settings are you using, and can you give more details on the error you are seeing?

**Comment by axandreo** [comment]
Great! Maybe it does have something to do with the versions then because all I did was download what is currently up on github. The only settings I changed during the export was in Animations. I made sure all eligible objects exported their animations.  It is exporting in gltf 2.0 . I am using blender 2.79 and I am on a mac. I'm sorry but unfortunately I don't know what else I can give you or where else I should be looking. Do you have any suggestions on where I could dig deeper?

**Comment by Kupoman** [comment]
That is helpful information. I believe you are encountering issue #125. I am going to close this issue as a duplicate. If you feel this issue is something different, feel free to reopen it.
