### ISSUE TITLE
Exported .gltf file contains data from previously failed exports

### ISSUE THREAD

**Issue by onox** [Kupoman/blendergltf#13]
1. Try to export a large file that fails to export. For example, one that produces the following exception: `struct.error: ushort format requires 0 <= number <= (32767 * 2 + 1)`.
2. Ctrl-n to reset Blender to the default state and then open a small .blend file that can be exported successfully.
3. Export the small .blend file

The exported .gltf will now contain in addition to the expected accessors, buffer views, and buffers, also tons of accessors, buffer views, and buffers from the previous model that failed to export.

Meshes, nodes, and scenes seem to be OK.

**Comment by Moguri** [comment]
I was not able to reproduce the issue, but I did see a problematic part of the code that could cause the types of problems you described. Can you test 1e8c730cb221d8c57f66327b973b63d0562dc7ec and see if it solves the problem for you?

**Comment by onox** [comment]
Seems to have fixed it :+1:
