### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'bones'

### ISSUE THREAD

**Issue by funwithtriangles** [Kupoman/blendergltf#137]
I am occasionally coming across the following error message when exporting from Blender:
![screen shot 2018-04-12 at 23 19 59](https://user-images.githubusercontent.com/1876324/38707221-60e9860e-3ea8-11e8-84d6-d971b2092618.png)

I am finding it very hard to understand what is going on, so unfortunately I can't produce an isolated case. However I have attached the Blender file that is causing the issue.
[boner-error.blend.zip](https://github.com/Kupoman/blendergltf/files/1905184/boner-error.blend.zip)

**Comment by Kupoman** [comment]
I have pushed a fix for this into a new 1.2.1 branch.

**Comment by Kupoman** [comment]
This fix is also now available in master.
