### ISSUE TITLE
Question about keyframes...

### ISSUE THREAD

**Issue by ladiszlai** [Kupoman/blendergltf#140]
Okay so I have an animated cube with 5 keyframes in 70 frames in my blend file:
https://files.fm/u/ujs4w23g

As you can see:
![nevtelen](https://user-images.githubusercontent.com/6253595/39955710-41710304-55d4-11e8-9a2e-fed2c7bfa072.jpg)

Exported to glTF: https://pastebin.com/cD6Kpmii

My question is why I have **"count" : 70** in the keyframe time accessor (input) ? Shouldn't be it just **"count" : 5** ? For my project what I am working I need the correct keyframes, because I can't calculate them if it is storing all of the frames...

**Comment by Kupoman** [comment]
This exporter generates a keyframe for every frame of the animation. This allows it to properly handle constraints (such as IK) and various interpolation modes between keyframes.

**Comment by ladiszlai** [comment]
And is there any setting that make only my keyframes ?

**Comment by Kupoman** [comment]
No, this exporter always bakes every frame of the animation. I believe the Khronos exporter exports key frames instead of baking the animations.
