### ISSUE TITLE
Ngons are not triangulated properly

### ISSUE THREAD

**Issue by AlbertoElias** [Kupoman/blendergltf#142]
![image](https://user-images.githubusercontent.com/913117/40590772-41a7e396-6205-11e8-9bc5-c3d823074ed5.png)

So that's how this avatar's eyes look when loading the exported scene in https://gltf-viewer.donmccurdy.com/. I have moved the eyes slightly forward so that you can notice the error in the eyes and in the holes in the face.

This is how it looks like in Blender
![image](https://user-images.githubusercontent.com/913117/40590780-8446208c-6205-11e8-89bb-03be9ae63a89.png)

It looks fine when using the Khronos exporter. I'm attaching the blend file and exported gltf file. Let me know if there is anything I can do, thanks!

[gltfexportererror (2).zip](https://github.com/Kupoman/blendergltf/files/2043029/gltfexportererror.2.zip)

**Comment by Kupoman** [comment]
It looks like a problem with Ngons. If I convert the head mesh to triangles (ctl+t in edit mode) the model exports fine. Mesh exporting will need to be better about triangulating meshes automatically so things just work in cases like this.

**Comment by AlbertoElias** [comment]
Oh, interesting, thanks for taking a look into it
