### ISSUE TITLE
Option to personalise name prefixes

### ISSUE THREAD

**Issue by AlbertoElias** [Kupoman/blendergltf#143]
I've noticed that exported animations and Bones come with prefixes. This makes it hard for my code to work nicely with these GLTF models. Would it be possible to add an option to modify and remove this prefixes? Thanks

**Comment by Kupoman** [comment]
I removed the prefixes so the glTF name property should now match the name from Blender. Is that sufficient for your use case, or do you need the ability to specify a non-empty custom prefix?

**Comment by AlbertoElias** [comment]
It is sufficient for my use case, yes. I was suggesting the prefix change in case there was a reason for having that prefix. Thanks!
