### ISSUE TITLE
Multiple Action support

### ISSUE THREAD

**Issue by ghost** [Kupoman/blendergltf#144]
Hey,

first: thank you very much for this exporter and all the work you put in there.

My question: Since I'm currently writing my bachelor thesis about exporting a 3D scene from Blender into Three.js applications using glTF, I'm searching for a way to have multiple actions for one object. I guess, it's easier to give a short example:
A cube that can move and/or rotate, having two checkboxes one saying "Move_Cube" and the other "Rotation_Cube". Is this possible. Am I missing out something?
Best regards and thank you,
Jakob

**Comment by Kupoman** [comment]
As long as the Action Editor in Blender lists multiple actions for the object, and the appropriate animation setting in the exporter is set to "All Eligible", all actions for an object should export. The default for objects is "Active Only", so you will need to change that setting for objects. Armatures and Shape Keys default to "All Eligible".
