### ISSUE TITLE
Emissive Factor in PBR panel retains only Value the but gltf spec says it's a RGB color

### ISSUE THREAD

**Issue by hugoam** [Kupoman/blendergltf#145]
I guess everything is in the title : 
The PBR export panel doesn't allow to set a color for emissive factor, but only a value, whereas the glTF spec says it's indeed a color, not only a value/factor : https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#materialemissivefactor

**Comment by Kupoman** [comment]
The emissive factor is exported as an RGB vector. The panel restricts emissive factor to a single value because it is tied to Blender's emit value, which is a single value.
