### ISSUE TITLE
Add "selection only" checkbox

### ISSUE THREAD

**Issue by emackey** [Kupoman/blendergltf#17]
Hi, awesome work on this glTF exporter so far!  Can I make a small feature request?

Please add a `Selection only` checkbox, similar to the STL exporter in Blender, such that only the selected objects are written to the exported file.  This would help for example when you need to create a file that just has a mesh or a model but no lights or cameras, etc.  Thanks!

**Comment by Kupoman** [comment]
This would certainly be a good option to have. I want to go through the settings and do a general clean up pass on them. If I don't get to this setting sooner, I'll add it in at that time.
