### ISSUE TITLE
corrupted normals + vertices data in single triangle

### ISSUE THREAD

**Issue by feiss** [Kupoman/blendergltf#30]
Hi! Trying the exporter with a single triangle, but I cannot make it work. 

[I already asked in the threejs repo](https://github.com/mrdoob/three.js/issues/10056), and there are chances that the problem relies in the exporter: I've just tried, and [cesiumjs](http://cesiumjs.org/convertmodel.html) viewer/converter fails trying to load the gltf.

Please go to the issue in threejs repo for all the details

Blender 2.77a

**Comment by yrns** [comment]
As I mentioned it the other thread, I think I have a fix for the importer. If you're desperate you can try the exporter here in the other branch, which might have an option for un-interleaved buffers. I never tried it.

**Comment by Kupoman** [comment]
The threejs_improvements branch of blendergltf has an option for exporting un-interleaved buffers. It also has some better material support. At this point I would recommend using that branch instead of master for most users, and I plan to merge it back into master soon.

**Comment by Kupoman** [comment]
The threejs_improvments branch has now been merged into master. I have also actually exposed the option for interleaving vertex data to the UI. The option was previously just in the module.

**Comment by feiss** [comment]
Awesome, thank you very much, I will give it a try and report

**Comment by Kupoman** [comment]
Any updates on this?

**Comment by yrns** [comment]
The three.js issue was closed as fixed. I haven't tested importing un-interleaved meshes with the new option yet.

**Comment by stevenvergenz** [comment]
I've tested it, it works. This issue can probably be closed.
