### ISSUE TITLE
Does it support skeletal meshes and animation export yet ?

### ISSUE THREAD

**Issue by motorsep** [Kupoman/blendergltf#32]
This looks very promising!

Does it support skeletal meshes and animation export yet ?

Thanks

**Comment by HeadClot** [comment]
Curious about this as well :)

**Comment by Moguri** [comment]
blendergltf supports skeletal meshes and a custom BLENDER_actions extension, but does not currently support regular glTF animations.

**Comment by motorsep** [comment]
> blendergltf supports skeletal meshes and a custom BLENDER_actions extension, but does not currently support regular glTF animations.

So in other words only static non-skeletal meshes end up in glTF ? If not that, could you please clarify ?

**Comment by Kupoman** [comment]
Skeletal meshes will also end up in the glTF including bones and their weights. The actual animations themselves are not currently exported in a way that follows the spec. I have opened issue #33 for adding this feature.
