### ISSUE TITLE
Add support for glTF animations

### ISSUE THREAD

**Issue by Kupoman** [Kupoman/blendergltf#33]
Currently glTF skins are exported, but not animations. We have the BLENDER_action extension for BlenderPanda, but we need to support specification compliant animations.

**Comment by Kupoman** [comment]
Added the animation branch for working on this. It's a bit messy right now, but I have had some success loading animations in Three.js.

**Comment by Kupoman** [comment]
After some clean up, I have merged the animation branch into master. I am sure there will be some further work fixing specific cases, but this issue is completed.

**Comment by caseyyee** [comment]
@Kupoman I'm having troubles exporting basic keyframe animations and loading into three.js.   The readme under Export Actions (which does not show for me) seems to suggest that I may need to "write animation data as individual actions ".  I'm unclear how this is done, as it also seems to suggest using a custom BLENDER_actions extension.   

Any guidance would be super helpful!

Thanks!

**Comment by Kupoman** [comment]
@caseyyee The documentation is out of date. The BLENDER_actions extension is no longer used, and the option for enabling it has been removed. Right now, animations always export. If you have a blend file that is not exporting correctly, please open a new issue with it.

**Comment by koliyo** [comment]
I get the same problem. I am very much a beginner with Blender so maybe I have done some obvious error. Anyway, I'm attaching a zip containing the blend file as well as the exported gltf. The box has three keyframes with different positions.

But when I inspect the loaded animation in the browser console I only get two keyframes, and both have same object positions.

```
> a.tracks
[VectorKeyframeTrack, QuaternionKeyframeTrack, VectorKeyframeTrack]
> a.tracks[0]
VectorKeyframeTrack {name: "Cube.position", times: Float32Array(2), values: Float32Array(6), createInterpolant: function}
> a.tracks[0].times
Float32Array(2) [0, 2.1666667461395264]
> a.tracks[0].values
Float32Array(6) [0, 7.269589900970459, 4.2343854904174805, 0, 7.269589900970459, 4.2343854904174805]
```


[box_anim.zip](https://github.com/Kupoman/blendergltf/files/935113/box_anim.zip)
