### ISSUE TITLE
THREE.js may now support interleaved vertex data?

### ISSUE THREAD

**Issue by donmccurdy** [Kupoman/blendergltf#35]
I assume that is what is described in [GLTFLoader.js#L739-L768](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js#L739-L768), and a quick test looks OK.

EDIT: Well, actually that code is not in a stable release yet. I was testing against `dev` branch.

**Comment by Kupoman** [comment]
I have updated the readme with this information. Thanks for pointing it out.

**Comment by mrdoob** [comment]
Interleaved support code was merged to master last week ✌️
