### ISSUE TITLE
Share vertices when possible

### ISSUE THREAD

**Issue by stevenvergenz** [Kupoman/blendergltf#39]
This exporter (and every other exporter/converter I've found) currently outputs each vertex once for every face it's a part of. This maximizes compatibility, and it's guaranteed to work, but it adds unnecessary bloat to the file in many cases. The exporter should check to see if a given vertex can be shared (i.e. no per-face normals/colors/UVs), and only output it once in that case.

If no one is available to work on this, I might just do this myself. I've done some Python before, but no Blender scripting, so we'll see how it goes.

**Comment by Kupoman** [comment]
This exporter should already combine duplicate vertices. In blendergltf, two vertices are considered duplicated if their normal, color, and uv coordinates match. This is accomplished in the code by the __hash__ and __eq__ methods on the Vertex class in combination with the dictionary comprehension (could probably use a set comprehension instead) that is currently on line 540 of the mesh conversion code in blendergltf.py.

Have you confirmed that vertex sharing is not working for you?

**Comment by stevenvergenz** [comment]
I've attached an example. The index buffer starts right at the beginning of the binary blob. and they don't repeat, they just count up to the buffer size. The mesh itself is an icosphere, so every vertex is shared by 5-6 faces. There are a few vertices with per-face UVs, but only at the poles and along one seam.

[sphere-raw.zip](https://github.com/Kupoman/blendergltf/files/695078/sphere-raw.zip)

**Comment by stevenvergenz** [comment]
Only after being parsed in Three.js. Let me examine the actual index buffer pre-parse, I'll get back to you.

**Comment by stevenvergenz** [comment]
Okay, I've dug into this a bit. The output does have a vertex index, and the contents of that buffer are not sequential, but no values repeat. So there are indeed no shared vertices. Here's my test file: [no-shared-vertex.zip](https://github.com/Kupoman/blendergltf/files/696978/no-shared-vertex.zip)

**Comment by stevenvergenz** [comment]
Aha, I think I've found it. The output vertex data is coming from `mesh.loops`, which is inherently per-face.

**Comment by stevenvergenz** [comment]
It turns out this is a more complicated issue than I thought. I'm going to close this issue, and open a new one to discuss some sort of smooth normal vs face normal option.
