### ISSUE TITLE
Option to output smooth normals

### ISSUE THREAD

**Issue by stevenvergenz** [Kupoman/blendergltf#40]
Currently, the glTF exporter outputs one vertex for every loop of every polygon. This preserves sharp edges at polygon seams, but dramatically increases the size of the resulting model when polygons share lots of vertices. I propose an option that would prevent vertex duplication by outputting "smooth" vertex normals instead of face normals per vertex. Alternatively, the exporter could decide whether to split edges based on the shading mode ("smooth" or "flat").

**Comment by stevenvergenz** [comment]
I've submitted a PR for this. Check it out when you get a chance.

**Comment by Kupoman** [comment]
Best not to close this until it is actually resolved (e.g. after merging a pull request).

I am still not sure what you are asking for. I just exported two icospheres, one set to smooth shading and the other set to flat shading in Blender. Comparing the vertex and triangle counts in Blender with the buffer sizes in the glTF output, it all looks correct to me. I loaded the glTF file and I saw one smooth and one flat shaded icosphere. As far as I can tell, duplicate vertex removal and normals are being handled correctly.

**Comment by stevenvergenz** [comment]
Could you explain that? Every model I export through this addon has exactly `3 * face_count` vertices, as measured by the size of the `position` attribute buffer. Since each face has exactly three vertices, that means that no two faces share a vertex.

My PR is less about removing duplicate vertices as causing them, so they can be removed. Vertices will never be removed unless they are exactly the same, that much is correct. However, given the way vertices are generated, they are almost never exactly the same because they use face normals, and normals are used in the comparison.

This PR creates certain circumstances under which vertex normals are used instead of face normals. Under those circumstances, adjacent faces will use the exact same vertex in the buffer, instead of creating their own copy with its own normal. This means an icosphere with 20,480 faces in blender will output a glTF file with 10,242 vertices instead of 61,440. (I'm only using an icosphere as an example because the vertex share rate is high. This approach can apply to all models.)

**Comment by stevenvergenz** [comment]
I'm open to a real-time conversation if you'd like. It's hard to explain without knowing what you don't understand. I'm on Slack ([register](https://altspacevr-slackin.herokuapp.com/))

**Comment by stevenvergenz** [comment]
**sigh** I just figured out what you were talking about. When a face has `use_smooth` set, the loop normals become the vertex normals instead of the face normals. So your code works as-is, without having to explicitly switch them in the exporter. I just needed to hit the "smooth" button in the toolbox.

Two days down the drain. Oh well, at least I learned some Blender-foo :)
