### ISSUE TITLE
Separating BRTE and Exporter code

### ISSUE THREAD

**Issue by stevenvergenz** [Kupoman/blendergltf#50]
Would you be supportive of an effort to separate the exporter code to a separate repo? Currently, the exporter will output virtually all data-blocks in a scene, regardless of whether or not they are used. In Issue #37 you explain that it does this to support the BRTE data transport use case, but it can produce grossly sub-optimal .gltf files with large scenes. Even zero-user meshes are exported.

My users need a solid export tool. I don't want to be divisive, but this seems like the cleanest solution. What do you think?

**Comment by Kupoman** [comment]
This repository was created when the glTF exporting capabilities were separated from BRTE. The BRTE code is in its own [repository](https://github.com/Kupoman/BlenderRealtimeEngineAddon). I'll add a comment to #37 about how to handle BRTE in this case.
