### ISSUE TITLE
Texture coordinates flipped in Three.js

### ISSUE THREAD

**Issue by stevenvergenz** [Kupoman/blendergltf#59]
For some reason, models exported with this addon display with flipped V coordinates in Three.js compared to the reference models in Three.js. Investigation pending.

**Comment by Kupoman** [comment]
I don't think it is the UV coordinates, I think the images are flipped on the Y axis. I think this may have something to do with WebGL, but I have not done much investigation on it yet.

**Comment by Kupoman** [comment]
Found a note in the spec under [images](https://github.com/KhronosGroup/glTF/blob/master/specification/1.0/README.md#images) about y axis flipping.

We can use the profile setting to control a fix, such as flipping images for the Web profile. Flipping the UV coordinate would probably be the easiest solution, while flipping images might be the more correct solution.

**Comment by stevenvergenz** [comment]
Oh, good find! I think flipping the images themselves (unless they're embedded) would be cumbersome. Maintaining two copies of every image in the scene would be confusing I think. I'm totally in favor of flipping the UV coordinates `if asset_profile == 'WEB'`
