### ISSUE TITLE
Split large meshes

### ISSUE THREAD

**Issue by Moguri** [Kupoman/blendergltf#6]
Meshes that have more indexes than can be represented by a short datatype need to be split into multiple primitives. Integer-sized indexes are not currently supported by the glTF spec.

**Comment by onox** [comment]
1.0.1 of the spec is going to allow 5125 (UNSIGNED_INT) as a componentType for accessors used only by [`primitives.indices`](https://github.com/KhronosGroup/glTF/tree/1.0.1/specification#reference-primitive.indices) if the OES_element_index_uint extension is used. See [accessor.componentType](https://github.com/KhronosGroup/glTF/tree/1.0.1/specification#accessorcomponenttype-white_check_mark).

Using this type could be controlled by a checkbox when exporting.

**Comment by Kupoman** [comment]
Since we have code in master to handle large meshes by using integer indices, I am closing this issue.
