### ISSUE TITLE
How are you merging these pull requests?

### ISSUE THREAD

**Issue by stevenvergenz** [Kupoman/blendergltf#60]
It's so weird, my changes are being added to master, but the branch itself is not listed as a parent, so it looks non-merged. What's your process for merging PRs?

**Comment by Kupoman** [comment]
I have been using the squash and merge button on GitHub. I'm not sure if there is a best practice for merging pull requests. I chose the squash and merge option to avoid getting clean up and merge commits in with a pull request.

**Comment by stevenvergenz** [comment]
"Squash" and merge? I'm unfamiliar with the squash operation. Is that a button on GitHub for Windows or something? I've never seen it on the site.

**Comment by Kupoman** [comment]
It is one of three options in the GitHub web interface for merging a pull request. The other options are a regular merge, or to rebase and merge. Squashing is a Git thing for combining commits. If I recall correctly, you can do it while rebasing.

**Comment by stevenvergenz** [comment]
Oh, I've never noticed that drop down before lol. I always create merge commits so the history is preserved.
