### ISSUE TITLE
Minify exported JSON

### ISSUE THREAD

**Issue by stevenvergenz** [Kupoman/blendergltf#61]
The generated identifiers are quite verbose, producing larger than necessary files. I propose a setting that would compact all the identifiers in the file while preserving the necessary links. Perhaps it could share an option with "Pretty-print JSON"? So `material_Material.001` and its ilk would be shortened to a single-character random identifier.

**Comment by Moguri** [comment]
glTF 2.0 will be changing from objects to arrays, which will remove the keys entirely: https://github.com/KhronosGroup/glTF/issues/831

**Comment by Kupoman** [comment]
@stevenvergenz Are you fine with closing this issue and letting it be resolved by glTF 2.0 support?
