### ISSUE TITLE
Enable add-on causes error

### ISSUE THREAD

**Issue by caseyyee** [Kupoman/blendergltf#62]
Following readme instructions, I get:

![image](https://cloud.githubusercontent.com/assets/1560884/22991314/b3341412-f370-11e6-8bc1-8090f2362c68.png)

**Comment by Moguri** [comment]
This syntax requires Python 3.5 ([details here](https://docs.python.org/3/whatsnew/3.5.html#pep-448-additional-unpacking-generalizations)), and I think 2.76 was still Python 3.4 (can confirm by following the instructions [here](http://blender.stackexchange.com/questions/18519/where-can-i-find-what-version-of-python-is-bundled-with-certain-blender-versions)?). If Blender 2.76 is using Python 3.4, we'll need to either bump our minimum Blender version, or make the code Python 3.4 compatible.

**Comment by caseyyee** [comment]
Ended up upgrading my version of blender.
This seems to have worked :)   I was indeed using 3.4 version of Pthyon.
