### ISSUE TITLE
Document BLENDER_physics extension

### ISSUE THREAD

**Issue by Kupoman** [Kupoman/blendergltf#63]
This documentation should match the documentation for official glTF extensions.

**Comment by stevenvergenz** [comment]
Requested reservation of the BLENDER vendor prefix in https://github.com/KhronosGroup/glTF/issues/865

**Comment by emackey** [comment]
Request approved in KhronosGroup/glTF#866

**Comment by Kupoman** [comment]
Great! I'll get to work on the documentation this weekend.

**Comment by Moguri** [comment]
BLENDER_physics has been documented. However, we have some open issues to improve the extension.
