### ISSUE TITLE
exporter overwrites existing buffer_combined.bin files without prompt

### ISSUE THREAD

**Issue by WACOMalt** [Kupoman/blendergltf#64]
In the proccess of exporting multiple gltf files one after the other, I discovered that the exporter names all of them "buffer_combined.bin" (Which would be great to customize in settings or have it use the gltf filename as a base) and if this file already exists it will overwrite without prompting.

**Comment by Kupoman** [comment]
I am not sure if we can get Blender to warn on overwriting supporting files, but we can at least make sure the combined buffer has a name based on the gltf filename to reduce possible collisions.
