### ISSUE TITLE
Error exporting a model

### ISSUE THREAD

**Issue by hilliardkc** [Kupoman/blendergltf#66]
I'm getting this error message when trying to export a fairly complex blender file as a gltf:
```
Traceback (most recent call last):
File ".../Blender/2.78/scripts/addons/blendergltf-master/__init__.py", line 175, in execute data = used_only(data)
File ".../Blender/2.78/scripts/addons/blendergltf-master/filters.py", line 76, in used_only slot.texture for slot in mat.texture_slots.values()
AttributeError: 'NoneType' object has no attribute 'texture_slots'

location: <unknown location>:-1
```

**Comment by stevenvergenz** [comment]
My guess is that you're trying to export a mesh that has no material. This is intended behavior, as glTF requires materials for all meshes. If you're so inclined, I can show you what to change so it outputs the mesh name that's erroring out. In the meantime, I'll fix this up so it throws a more descriptive error message.

**Comment by roxlu** [comment]
Having a similar issue with this blend file. 
[vw.blend.zip](https://github.com/Kupoman/blendergltf/files/959525/vw.blend.zip)

And another one:
http://www.blendswap.com/blends/view/6463
