### ISSUE TITLE
BLENDER_physics: Support collision layers

### ISSUE THREAD

**Issue by Moguri** [Kupoman/blendergltf#68]
We should support some form of layers or groups/masks in BLENDER_physics. Blender's RigidBodyObjects only expose a layer option, but its game settings expose the full group/mask concept that Bullet supports.

**Comment by stevenvergenz** [comment]
For reference, I've been reading about how some popular engines handle this topic.

| Engine | Object Membership | Collide test |
|-----------|-------------------|-----------|
| [Bullet](http://www.bulletphysics.org/mediawiki-1.5.8/index.php/Collision_Filtering) | 0+ groups | object-group
| [Unity](https://docs.unity3d.com/Manual/LayerBasedCollision.html) | 1 group | group-group
| [Unreal](https://www.unrealengine.com/blog/collision-filtering) | 1 group | object-group OR group-group

Our goal shouldn't be to implement physics layers though, just allow content authors to provide enough information for consumers to infer the correct alignment with their own collision system. So I think it is sufficient for objects to provide layer membership information, and nothing else. The consumers must decide how those memberships interact.

**Comment by stevenvergenz** [comment]
Though speaking of alignment, it occurs to me that it might be useful to allow glTF producers to name the collision layers. The added semantic information may be helpful for consumers to correctly align model layers with engine layers.

**Comment by Kupoman** [comment]
I think we should go with masks and groups like Bullet, and just convert the Blender collision layers into group and mask settings.
