### ISSUE TITLE
BLENDER_physics: Export scene settings

### ISSUE THREAD

**Issue by Moguri** [Kupoman/blendergltf#69]
We should explore whether we want to export per-scene physics settings such as gravity, and what this looks like.

One of the issues with exporting a gravity setting is defining units. We could say that BLENDER_physics exports a gravity setting as an acceleration value in m/s^2, but that assumes that one glTF unit will be represented as 1m in the engine consuming the file.

**Comment by stevenvergenz** [comment]
I think 1u = 1m is probably a safe assumption, given [the spec](https://github.com/KhronosGroup/glTF/tree/master/specification/1.0#coordinate-system-and-units):

> The units for all linear distances are meters.

**Comment by Kupoman** [comment]
I think scene settings are fine. Anything to put in there other than gravity?

**Comment by Moguri** [comment]
Gravity has been added with 282d54e7178f1a8e8c96654f075d509bb373bdd6.

@stevenvergenz, if you think more settings need to be added, or have any concerns with the spec update, please open a new issue.
