### ISSUE TITLE
BLENDER_physics: Explore better ways to represent dimensions

### ISSUE THREAD

**Issue by Moguri** [Kupoman/blendergltf#70]
The simple dimensions concept we currently use has the following issues:

* Assumes Z-Up physics engine, but [glTF is Y-Up](https://github.com/KhronosGroup/glTF/tree/master/specification/1.0#coordinate-system-and-units)
* Relies on consuming engines to extract information from dimensions (e.g., pick a dimension to treat as radius/height, perform extra math steps, etc.)
* Inconsistent use of scale and lack of transform information. Blender's dimensions have scale applied, but there is no clear way to determine scale or transforms of mesh shapes. Further more, with no transform, we cannot easily specify offsets.

However, it does provide the following benefits:

* Easy to export
* Does not make assumptions about how the consuming physics engines defines shapes

**Comment by stevenvergenz** [comment]
Don't forget to take other export engines into account. Our current system is easy for Blender, but might not be for other exporters. Z-Up is pretty uncommon among game engines.

**Comment by Kupoman** [comment]
I think we can define the dimensions in a local space, and update the spec to be clear about applying the node's transform to the physics shape. This local space will treat the Z-axis as the height axis as described in the section on extracting shape parameters from the dimensions.

**Comment by Moguri** [comment]
Closed by PR #88
