### ISSUE TITLE
Cleanup - Class-based parsing

### ISSUE THREAD

**Issue by stevenvergenz** [Kupoman/blendergltf#73]
I want to float an idea by you guys @Kupoman @Moguri before I actually start work on it. I think it's a good idea.

The `export_gltf.py` file is getting too large, and it will only get larger as new features are added. I propose moving the parsing code for each type into classes that inherit this base:

```python
class GLTFSerialBase:
    def __init__(self, context, source):
        '''convert source to gltf format, using context
        context contains the object lookup table, and glTF structures so far defined'''
        pass

    def __dict__(self):
        '''returns the converted glTF-compliant data structure'''
        return {}

    def __bytes__(self):
        '''returns the binary content of this object, or None if no binary'''
        pass
```

I expect this to greatly improve the readability of the code base. What do you think?

**Comment by stevenvergenz** [comment]
Okay, the more I look into this, the more work I think this is going to be. The current code all overlaps with itself, so we can't separate certain pieces without significant work. Especially w.r.t. objects that don't have Blender equivalents, i.e. the data classes. I still think it's worth doing, but it'll require significant buy-in.

**Comment by Moguri** [comment]
I do not believe there is a huge need to break up the file at the moment. Moving some of the utility classes like Vertex and Buffer is fine (as you've done #74). However, I like keeping most of the export code together for now. I also prefer the more functional style of the exporter over wrapping everything in classes.

**Comment by stevenvergenz** [comment]
I can understand the argument for functional over object-oriented, but the sheer volume and density of that file is extremely intimidating for external developers, myself included. Could you explain your stance on not breaking up the monolith?

**Comment by Moguri** [comment]
This file will be less than 1,000 lines of code when the utility classes get moved, which I don't find to be very large. The function names all (or, at least, should all) line up with the top level objects in the glTF spec, so it should be easy to find the part of the code you want to look at. I prefer searching and navigating one file rather than having to deal with multiple files.

**Comment by Kupoman** [comment]
At this time, we are not interested in this kind of refactor. Thank you for your suggestion and feedback. As the code base continues to grow, we will be keeping ideas like this in mind to ensure the code base stays maintainable.
