### ISSUE TITLE
Exporter is writing out bad gltf meshes

### ISSUE THREAD

**Issue by no-tably** [Kupoman/blendergltf#79]
Hi,

I'm getting issues exporting the mesh even when just doing it with the simplest settings or more custom settings. Not sure why but it won't handle an Icosphere or even susan without the mesh exploding.

![blend_model](https://user-images.githubusercontent.com/23611481/27768267-bec025d2-5ec3-11e7-89c8-9b649e253940.PNG)
![file](https://user-images.githubusercontent.com/23611481/27768268-bec0c776-5ec3-11e7-9315-e4b1bbc387ed.PNG)
![gltf_messed](https://user-images.githubusercontent.com/23611481/27768269-bec160fa-5ec3-11e7-903b-e3ccc3c527e3.PNG)
![settings](https://user-images.githubusercontent.com/23611481/27768270-bec29420-5ec3-11e7-8e1f-4e4ccef5b390.PNG)

Thanks!

**Comment by Moguri** [comment]
Try disabling "Interleave Vertex Data" in the Mesh options. It looks like the importer you're using may be assuming (incorrectly) that the data is non-interleaved.

**Comment by no-tably** [comment]
Ahh that makes sense. I just managed to get it working with that. what are the benifits of leaving on Interleave Vertex Data if it is interpreted correctly?

**Comment by Kupoman** [comment]
At least at one point, it was pretty common practice to interleave vertex data for performance, and [Apple still recommends doing this on iOS](https://developer.apple.com/library/content/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/TechniquesforWorkingwithVertexData/TechniquesforWorkingwithVertexData.html). That being said, it seems that [some people disagree with that](https://anteru.net/blog/2016/02/14/3119/index.html). In the end, it probably does not make a difference for general rendering. It seems de-interleaved data is better supported with glTF loaders (my guess is that most of the example models store vertex data this way), so we may want to consider changing our default.

However, that would be a new issue. Can this issue be closed, or is there still something that is not working correctly?

**Comment by no-tably** [comment]
Sure thing! sorry it took me so long to get back to you.
