### ISSUE TITLE
Add support for PBR materials

### ISSUE THREAD

**Issue by Kupoman** [Kupoman/blendergltf#80]
We need a way to handle PBR materials to better support the glTF 2.0 specification. Since Blender 2.7x does not support PBR natively, we will need to add a material panel for PBR settings. The setting for this panel should be linked with Blender materials to give a rough preview to the user.

**Comment by stevenvergenz** [comment]
Does this mean that this project is still being maintained? I had assumed it was superseded by the Khronos exporter.

**Comment by Kupoman** [comment]
Yes, this project is stil being maintained. The Khronos exporter was made without our participation or knowledge. With its close ties to the [BlenderPanda](https://github.com/Moguri/BlenderPanda) project, this exporter has some different goals to the Khronos exporter. We are open to collaboration between the two exporter projects, but, for now, we do not see a reason to stop maintaining this exporter.
