### ISSUE TITLE
Add support for KHR_material_cmnBlinnPhong extension

### ISSUE THREAD

**Issue by Kupoman** [Kupoman/blendergltf#83]
There is a discussion on the extension here: https://github.com/KhronosGroup/glTF/issues/947
And a pull request here: https://github.com/KhronosGroup/glTF/pull/1075

**Comment by Kupoman** [comment]
Removing from version 1.1 targets since the extension is not yet complete.

**Comment by Moguri** [comment]
Clearing the milestone on this until the spec is more stable/finalized.

**Comment by donmccurdy** [comment]
An update — `KHR_materials_common` and its proposed alternative, `KHR_materials_cmnBlinnPhong`, will not be created for glTF 2.0 at this time.

The strongest feedback from the community was around shadeless materials, so we are moving forward with the simpler `KHR_materials_unlit`:

- [Specification](https://github.com/KhronosGroup/glTF/pull/1163)
- [Demo viewer w/ patched support](https://khr-materials-unlit-ooddguuati.now.sh/)

The extension is not yet ratified, but Sketchfab and Facebook will begin using it shortly and the schema is unlikely to change — I think it would be safe to include with the next milestone here, and I have also [proposed it for the Khronos exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/160).

**Comment by Kupoman** [comment]
Closing this issue since this extension is unlikely to go anywhere. Thanks for the update @donmccurdy.
