### ISSUE TITLE
Add version filtering to extensions

### ISSUE THREAD

**Issue by Kupoman** [Kupoman/blendergltf#84]
Extensions should be able to specify compatible versions, and then the UI can use this information to only display extension for the currently selected glTF version.

This will be useful to avoid confusion with KHR_material_common and KHR_material_cmnBlinnPhong.

**Comment by Kupoman** [comment]
Since KHR_material_cmnBlinnPhong support was bumped from 1.1, I am bumping this too.

**Comment by Moguri** [comment]
Clearing the milestone for this. We'll add this back to the roadmap if/when we have an extension on the roadmap (e.g., KHR_material_cmnBlinnPhong) that needs this feature.

**Comment by Kupoman** [comment]
With the deprecation and eventual removal of glTF 1.0 0 support (#135), this is even less important. Closing out this issue since we are not likely to need this functionality for quite some time.
